#!/usr/bin/env python

import sys

import environment
from blitz import sync

if __name__ == "__main__":
	command = sys.argv[1]
	if len(sys.argv) > 2:
		tag = sys.argv[2]
		print "Blitzing %s nodes named/tagged '%s'\n\n" % (tag, command)
	else:
		tag = ""
		print "Blitzing all nodes '%s'\n\n" % command

	sync(command, tag)